sterc_1 animateSource["terc", 0];
sterc_2 animateSource["terc", 0];
sterc_3 animateSource["terc", 0];
sterc_4 animateSource["terc", 0];
sterc_5 animateSource["terc", 0];
sterc_6 animateSource["terc", 0];
sterc_7 animateSource["terc", 0];
sterc_8 animateSource["terc", 0];
sterc_9 animateSource["terc", 0];
hint "Odstřelovací cíle resetovány.";